import type { NextPage } from "next";
import Head from "next/head";

import styled from "styled-components";

const Title = styled.h1`
  color: ${props => props.theme.red[400]};
  font-size: 50px;
`;

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Planegazers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Title>sduifshafijsda hsadifsdahifjsdahfj</Title>
    </>
  );
};

export default Home;
